version: '3'

services:
  dev:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
    - '80:3000'
    volumes:
    - /app/node_modules
    - .:/app
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=s1mpl3
    command: ["nodemon", "./bin/www",]

  ftpd-server:
    image: stilliard/pure-ftpd:hardened
    ports:
      - '21:21'
      - '20:20'
      - '30000-30009:30000-30009'
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=test
      - FTP_USER_PASS=test
      - FTP_USER_HOME=/app

  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '80:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASS=s1mpl3
    command: ["node", "./bin/www"]
